### ISSUE TITLE
Remove font files from repo and use google fonts

### ISSUE THREAD

**Issue by archanks** [yoursweater/nbaheatcheck#1]
If you look at the fonts directory, you'll see it's quite heavy. It can make the site super slow on mobile give then amount to download to render the font. Google offers [Roboto](https://www.google.com/fonts#UsePlace:use/Collection:Roboto) and allows you to choose the character sets you need as well as the specific weights you need. This will keep size of fonts small and will be a good optimization in terms of page load.

**Comment by yoursweater** [comment]
I added a link to Google fonts and removed the massive fonts directory. Good catch!
